# Generated by Django 5.2.2 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='upcoming', max_length=20),
        ),
    ]
