# Generated by Django 5.2.2 on 2025-06-05 20:03

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations

from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_tags'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='events_even_descrip_9b2cb3_gin'),
        ),
    ]
