services:
  db:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.2

  web:
    build: .
    command: sh -c "uv run python manage.py migrate --no-input && uv run python manage.py runserver 0.0.0.0:80"
    restart: always
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

  celery-beat:
    restart: always
    build: .
    command: uv run celery -A apps beat --scheduler django --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis
      - web

  celery-worker-default:
    restart: always
    build: .
    command: uv run celery -A apps worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis
      - web

  celery-worker-priority:
    restart: always
    build: .
    command: uv run celery -A apps worker --loglevel=info --queues priority
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis
      - web
